[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aosp-rag"
version = "0.0.1"
description = "RAG PoC over AOSP"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["rag*"]
